### ISSUE TITLE
show tag values throwing ERR

### ISSUE THREAD

**Issue by jackzampolin** [influxdb/docs.influxdata.com#23]
Originally: https://github.com/influxdb/influxdb.com/issues/547

Is there some way I can send a trace or dump file for my database?
I'm using Influx 0.9.5.1.

See the problem:
[ksengal@csdev-ksengal influxdb]$ influx
Visit https://enterprise.influxdata.com to register for updates, InfluxDB server management, and monitoring.
Connected to http://localhost:8086 version 0.9.5.1
InfluxDB shell 0.9.5.1
% show databases

name: databases

name
_internal
cs

% use cs
Using database cs
% help
Usage:
connect host:port connect to another node
auth prompt for username and password
pretty toggle pretty print
use set current databases
format set the output format: json, csv, or column
precision set the timestamp format: h,m,s,ms,u,ns
consistency set write consistency level: any, one, quorum, or all
settings output the current settings for the shell
exit quit the influx shell

    show databases        show database names
    show series           show series information
    show measurements     show measurement information
    show tag keys         show tag key information
    show tag values       show tag value information

    a full list of influxql commands can be found at:
    https://influxdb.com/docs/v0.9/query_language/spec.html
% show series

name: fakeMeasurementName

_key fakeTagLabel1 fakeTagLabel2
fakeMeasurementName,fakeTagLabel1=fakeTagValue1,fakeTagLabel2=fakeTagValue2 fakeTagValue1 fakeTagValue2

% show tag keys

name: fakeMeasurementName

tagKey
fakeTagLabel1
fakeTagLabel2

% show tag values

ERR: error parsing query: found EOF, expected WITH at line 1, char 17 <~~ Error?
% SELECT * from fakeMeasurementName 
% <~~~~ Also, this should return something :(

What are the debugging commands available to help here?
Note, the data was inserted using golang code using v2 version of golang client api (pasting it here probably would not make sense).

Here I try to grab the entire series:

[ksengal@csdev-ksengal influxdb]$ curl -G 'http://localhost:8086/query?pretty=true' --data-urlencode "db=cs" --data-urlencode "q=SELECT value FROM fakeMeasurementName"
{
"results": [
{}
]
}

EMPTY, yet...

[ksengal@csdev-ksengal influxdb]$ influx
Visit https://enterprise.influxdata.com to register for updates, InfluxDB server management, and monitoring.
Connected to http://localhost:8086 version 0.9.5.1
InfluxDB shell 0.9.5.1
% use cs
Using database cs
% show series

name: fakeMeasurementName

_key fakeTagLabel1 fakeTagLabel2
fakeMeasurementName,fakeTagLabel1=fakeTagValue1,fakeTagLabel2=fakeTagValue2 fakeTagValue1 fakeTagValue2

%

**Comment by beckettsean** [comment]
fixed by https://github.com/influxdb/docs.influxdata.com/commit/6d71a3b244be69d2136222da567a050580da0fbd
